"""
Dashboard Service
Business-logic layer between the API endpoints and the repository.

Uses lead_repository (the singleton that already owns all Lead DB queries)
instead of the incompatible DashboardRepository generated by the other AI.

Raises only exception classes that exist in app.core.exceptions.
"""
import time
import uuid
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import logger
from app.core.exceptions import ServiceUnavailableException
from app.repositories.lead import lead_repository
from app.schemas.dashboard_schemas import (
    DashboardSummaryResponse,
    DistributionItem,
    DistributionResponse,
    RecentLeadItem,
    RecentLeadsResponse,
)

_DEFAULT_LIMIT = 10
_MAX_LIMIT = 100


class DashboardService:
    """
    All dashboard business logic.
    One instance per request (instantiated by FastAPI's Depends factory).
    """

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    async def get_summary(self, db: AsyncSession, user_id: uuid.UUID) -> DashboardSummaryResponse:
        """Return aggregated KPI metrics scoped to the authenticated user."""
        logger.info("Dashboard summary request | user_id=%s", user_id)
        t0 = time.perf_counter()

        try:
            stats = await lead_repository.get_dashboard_summary(db, user_id=user_id)
        except Exception as exc:
            logger.error("Failed to fetch dashboard summary | user_id=%s | error=%s", user_id, exc, exc_info=True)
            raise ServiceUnavailableException("Could not retrieve dashboard summary.") from exc

        elapsed = (time.perf_counter() - t0) * 1000
        logger.info("Dashboard summary returned | user_id=%s | total_leads=%d | elapsed_ms=%.2f",
                    user_id, stats["total_leads"], elapsed)

        if stats["total_leads"] == 0:
            logger.warning("Dashboard summary returned zero leads | user_id=%s", user_id)

        return DashboardSummaryResponse(**stats)

    # ------------------------------------------------------------------
    # Recent Leads
    # ------------------------------------------------------------------

    async def get_recent_leads(
        self,
        db: AsyncSession,
        user_id: uuid.UUID,
        limit: Optional[int] = _DEFAULT_LIMIT,
        offset: Optional[int] = 0,
    ) -> RecentLeadsResponse:
        """Return the most recently created leads with pagination."""
        limit = max(1, min(limit or _DEFAULT_LIMIT, _MAX_LIMIT))
        offset = max(0, offset or 0)

        logger.info("Dashboard recent-leads request | user_id=%s | limit=%d | offset=%d",
                    user_id, limit, offset)
        t0 = time.perf_counter()

        try:
            total, leads_data = await lead_repository.get_recent_leads_for_dashboard(
                db, user_id=user_id, limit=limit, offset=offset
            )
        except Exception as exc:
            logger.error("Failed to fetch recent leads | user_id=%s | error=%s", user_id, exc, exc_info=True)
            raise ServiceUnavailableException("Could not retrieve recent leads.") from exc

        elapsed = (time.perf_counter() - t0) * 1000
        logger.info("Dashboard recent-leads returned | user_id=%s | count=%d | elapsed_ms=%.2f",
                    user_id, len(leads_data), elapsed)

        return RecentLeadsResponse(
            total=total,
            limit=limit,
            offset=offset,
            leads=[RecentLeadItem(**lead) for lead in leads_data],
        )

    # ------------------------------------------------------------------
    # Status Distribution
    # ------------------------------------------------------------------

    async def get_status_distribution(self, db: AsyncSession, user_id: uuid.UUID) -> DistributionResponse:
        """Return lead counts grouped by pipeline status."""
        return await self._get_distribution(db, user_id, "status")

    # ------------------------------------------------------------------
    # Industry Distribution
    # ------------------------------------------------------------------

    async def get_industry_distribution(self, db: AsyncSession, user_id: uuid.UUID) -> DistributionResponse:
        """Return lead counts grouped by industry."""
        return await self._get_distribution(db, user_id, "industry")

    # ------------------------------------------------------------------
    # City Distribution
    # ------------------------------------------------------------------

    async def get_city_distribution(self, db: AsyncSession, user_id: uuid.UUID) -> DistributionResponse:
        """Return lead counts grouped by city."""
        return await self._get_distribution(db, user_id, "city")

    # ------------------------------------------------------------------
    # Shared helper
    # ------------------------------------------------------------------

    async def _get_distribution(
        self,
        db: AsyncSession,
        user_id: uuid.UUID,
        dimension: str,         # "status" | "industry" | "city"
    ) -> DistributionResponse:
        logger.info("Dashboard %s-distribution request | user_id=%s", dimension, user_id)
        t0 = time.perf_counter()

        try:
            if dimension == "status":
                raw = await lead_repository.get_status_distribution(db, user_id=user_id)
                # Raw rows: [{"status": ..., "count": ...}]
                buckets = [{"label": r["status"], "count": r["count"]} for r in raw]
            elif dimension == "industry":
                raw = await lead_repository.get_industry_distribution(db, user_id=user_id)
                buckets = [{"label": r["industry"], "count": r["count"]} for r in raw]
            else:  # city
                raw = await lead_repository.get_city_distribution(db, user_id=user_id)
                buckets = [{"label": r["city"], "count": r["count"]} for r in raw]
        except Exception as exc:
            logger.error("Failed to fetch %s distribution | user_id=%s | error=%s",
                         dimension, user_id, exc, exc_info=True)
            raise ServiceUnavailableException(f"Could not retrieve {dimension} distribution.") from exc

        elapsed = (time.perf_counter() - t0) * 1000
        total = sum(b["count"] for b in buckets)
        logger.info("%s-distribution returned | user_id=%s | buckets=%d | elapsed_ms=%.2f",
                    dimension, user_id, len(buckets), elapsed)

        if not buckets:
            logger.warning("%s-distribution returned no buckets | user_id=%s", dimension, user_id)

        return DistributionResponse(
            total=total,
            distribution=[DistributionItem(**b) for b in buckets],
        )


# Singleton — injected by FastAPI Depends factory in the endpoint file
dashboard_service = DashboardService()
