"""Tests for FidelityValidator — validates generated HTML fidelity to source."""
import pytest
from dataclasses import dataclass, field
from typing import List, Optional

from app.services.website_generator.fidelity_validator import FidelityValidator, FidelityIssue, FidelityValidationResult
from app.services.website_intelligence.schemas import WebsiteProfile
from app.services.markdown_engine.asset_manifest import AssetManifest, AssetManifestItem, AssetRole


def make_minimal_profile(**overrides) -> WebsiteProfile:
    """Build a WebsiteProfile with minimal required fields."""
    from pydantic import BaseModel
    from typing import List as TList, Optional as TOptional

    from app.services.website_intelligence.schemas import (
        BusinessInfo, ContactInfo, BrandIdentity, DesignLanguageResult,
        HeroInfo, TypographyInfo, ComponentStyles, ColorPalette, WebsiteProfile,
    )

    business = BusinessInfo(name="Test Cafe", industry="Coffee", description="A test coffee shop")
    contact = ContactInfo(emails=["hello@testcafe.com"], phones=["+1-555-0199"])
    brand = BrandIdentity(
        design_language=DesignLanguageResult(design_language="Modern"),
        hero=HeroInfo(headline="Best Coffee"),
        colors=ColorPalette(),
    )
    return WebsiteProfile(
        business=business,
        contact=contact,
        brand=brand,
        url="https://testcafe.com",
        **overrides,
    )


@pytest.fixture
def profile():
    return make_minimal_profile()


@pytest.fixture
def manifest():
    m = AssetManifest(
        items=[
            AssetManifestItem(
                original_url="https://testcafe.com/hero.jpg",
                absolute_url="https://testcafe.com/hero.jpg",
                role=AssetRole.HERO,
                section="hero",
                local_filename="hero.jpg",
            ),
            AssetManifestItem(
                original_url="https://testcafe.com/logo.png",
                absolute_url="https://testcafe.com/logo.png",
                role=AssetRole.LOGO,
                section="header",
                local_filename="logo.png",
            ),
        ],
        source_url="https://testcafe.com",
        total_count=2,
    )
    return m


class TestFidelityValidator:
    def test_empty_html_fails(self, profile):
        validator = FidelityValidator(profile)
        result = validator.validate("")
        assert not result.valid
        assert any(i.category == "empty_output" for i in result.issues)

    def test_valid_html_passes(self, profile):
        profile.contact.phones = ["+1-555-0199"]
        html = """
        <!DOCTYPE html>
        <html><head><title>Test Cafe</title></head>
        <body>
        <h1>Test Cafe</h1>
        <p>Welcome to our coffee shop serving espresso and latte.</p>
        <p>Email: hello@testcafe.com</p>
        <p>Phone: +1-555-0199</p>
        </body></html>
        """
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert result.valid, f"Issues: {[(i.category, i.detail) for i in result.issues]}"

    def test_missing_business_name(self, profile):
        html = "<html><body><h1>Wrong Name</h1></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "missing_business_name" for i in result.issues)

    def test_lorem_ipsum_detected(self, profile):
        html = "<html><body><p>Lorem ipsum dolor sit amet.</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "lorem_ipsum" for i in result.issues)

    def test_service_placeholder_detected(self, profile):
        html = "<html><body><h2>Service 1</h2><p>Service 2</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "service_placeholder" for i in result.issues)

    def test_leadforge_branding_detected(self, profile):
        html = "<html><body><p>Generated by LeadForge</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "leadforge_branding" for i in result.issues)

    def test_dummy_email_detected(self, profile):
        html = "<html><body><p>Contact: info@example.com</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "dummy_email" for i in result.issues)

    def test_dummy_phone_detected(self, profile):
        html = "<html><body><p>Call 123-456-7890</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "dummy_phone" for i in result.issues)

    def test_dummy_address_detected(self, profile):
        html = "<html><body><p>123 Main St</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "dummy_address" for i in result.issues)

    def test_preserves_contact_email(self, profile):
        html = "<html><body><p>Email: hello@testcafe.com</p><p>Phone: +1-555-0199</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert "hello@testcafe.com" in result.preserved_contact_emails
        assert result.preserved_contact_emails == ["hello@testcafe.com"]

    def test_missing_contact_email(self, profile):
        html = "<html><body><p>No contact info</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "missing_contact_email" for i in result.issues)

    def test_preserves_services(self, profile):
        from app.services.website_intelligence.schemas import ServiceCard
        profile.services = [ServiceCard(name="Espresso")]
        html = "<html><body><h3>Espresso</h3></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert result.preserved_service_count == 1

    def test_missing_services_flagged(self, profile):
        from app.services.website_intelligence.schemas import ServiceCard
        profile.services = [ServiceCard(name="Espresso"), ServiceCard(name="Latte")]
        html = "<html><body><p>No services here</p></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "missing_services" for i in result.issues)

    def test_approved_images_with_manifest(self, profile, manifest):
        html = """
        <!DOCTYPE html>
        <html><body>
        <h1>Test Cafe</h1>
        <img src="https://testcafe.com/hero.jpg" alt="Hero">
        <img src="https://testcafe.com/logo.png" alt="Logo">
        <p>Email: hello@testcafe.com</p>
        <p>Phone: +1-555-0199</p>
        </body></html>
        """
        validator = FidelityValidator(profile, manifest=manifest)
        result = validator.validate(html)
        assert result.approved_image_count >= 2
        assert len(result.broken_image_refs) == 0

    def test_unapproved_images_detected(self, profile, manifest):
        html = """
        <!DOCTYPE html>
        <html><body>
        <img src="https://testcafe.com/hero.jpg" alt="Hero">
        <img src="https://evil.com/virus.png" alt="Bad">
        </body></html>
        """
        validator = FidelityValidator(profile, manifest=manifest)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "unapproved_images" for i in result.issues)
        assert "https://evil.com/virus.png" in result.broken_image_refs

    def test_markdown_fences_detected(self, profile):
        html = "<html>```\nprint('hello')\n```</html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "markdown_fences" for i in result.issues)

    def test_no_visible_content(self, profile):
        html = "<html><body><div></div></body></html>"
        validator = FidelityValidator(profile)
        result = validator.validate(html)
        assert not result.valid
        assert any(i.category == "no_visible_content" for i in result.issues)

    def test_issue_dataclass(self):
        issue = FidelityIssue(category="test", detail="Something went wrong")
        assert issue.category == "test"
        assert issue.detail == "Something went wrong"

    def test_result_dataclass(self):
        result = FidelityValidationResult(valid=True)
        assert result.valid
        assert result.issues == []
        assert result.preserved_service_count == 0
