from app.services.website_intelligence.service import WebsiteIntelligenceService
from app.services.website_intelligence.repository import WebsiteIntelligenceRepository
from app.services.website_intelligence.schemas import (
    BrandIdentity,
    BrandPersonalityResult,
    BusinessInfo,
    CallToAction,
    ColorPalette,
    CompanySection,
    ComponentStyles,
    ComputedColor,
    ConsistencyReport,
    ContactInfo,
    ContrastPair,
    CtaButton,
    CtaLink,
    CTAInfo,
    DesignLanguageEntry,
    DesignLanguageResult,
    FAQ,
    FooterInfo,
    HeroInfo,
    HeroSection,
    HslColor,
    ImageAsset,
    LogoInfo,
    NavItem,
    NavigationInfo,
    NavigationItem,
    RgbColor,
    SEOInfo,
    SectionInfo,
    ServiceCard,
    ProductItem,
    QualityMetric,
    QualityMetrics,
    SocialLink,
    TeamMember,
    Testimonial,
    TrustSignal,
    Typography,
    TypographyInfo,
    WebsiteBlueprint,
    WebsiteLayout,
    WebsiteProfile,
    WebsiteIntelligenceResponse,
)
from app.services.website_intelligence.constants import WebsiteIntelligenceConstants
from app.services.website_intelligence.helpers import WebsiteIntelligenceHelpers

__all__ = [
    "WebsiteIntelligenceService",
    "WebsiteIntelligenceRepository",
    "WebsiteIntelligenceConstants",
    "WebsiteIntelligenceHelpers",
    "BrandIdentity",
    "BrandPersonalityResult",
    "BusinessInfo",
    "CallToAction",
    "ColorPalette",
    "CompanySection",
    "ComponentStyles",
    "ComputedColor",
    "ConsistencyReport",
    "ContactInfo",
    "ContrastPair",
    "CtaButton",
    "DesignLanguageEntry",
    "DesignLanguageResult",
    "FAQ",
    "FooterInfo",
    "HeroInfo",
    "HeroSection",
    "ImageAsset",
    "LogoInfo",
    "NavItem",
    "NavigationInfo",
    "NavigationItem",
    "ServiceCard",
    "ProductItem",
    "QualityMetric",
    "QualityMetrics",
    "SocialLink",
    "TeamMember",
    "Testimonial",
    "TrustSignal",
    "Typography",
    "TypographyInfo",
    "CtaLink",
    "CTAInfo",
    "SectionInfo",
    "WebsiteBlueprint",
    "WebsiteLayout",
    "WebsiteProfile",
    "WebsiteIntelligenceResponse",
]

website_intelligence_service = WebsiteIntelligenceService()
website_intelligence_repository = WebsiteIntelligenceRepository()