"""add website_intelligence table

Revision ID: 1a6f7a805ee9
Revises: e7f0a4b12c56
Create Date: 2026-07-06 18:58:58.011565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6f7a805ee9'
down_revision: Union[str, Sequence[str], None] = 'e7f0a4b12c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create website_intelligence table."""
    op.create_table('website_intelligence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_legal_name', sa.String(length=255), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('business_industry', sa.String(length=100), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('google_maps_url', sa.String(length=2083), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.String(length=50), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('website_summary', sa.Text(), nullable=True),
    sa.Column('brand_tagline', sa.String(length=500), nullable=True),
    sa.Column('brand_voice', sa.Text(), nullable=True),
    sa.Column('brand_unique_selling_points', sa.JSON(), nullable=True),
    sa.Column('logo_info_url', sa.String(length=2083), nullable=True),
    sa.Column('logo_info_format', sa.String(length=10), nullable=True),
    sa.Column('logo_info_has_transparency', sa.Boolean(), nullable=True),
    sa.Column('logo_info_width', sa.Integer(), nullable=True),
    sa.Column('logo_info_height', sa.Integer(), nullable=True),
    sa.Column('logo_info_dominant_colors', sa.JSON(), nullable=True),
    sa.Column('logo_info_position', sa.String(length=50), nullable=True),
    sa.Column('logo_info_retina_quality', sa.Boolean(), nullable=False),
    sa.Column('logo_info_is_favicon_fallback', sa.Boolean(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('color_primary', sa.String(length=20), nullable=True),
    sa.Column('color_secondary', sa.String(length=20), nullable=True),
    sa.Column('color_accent', sa.String(length=20), nullable=True),
    sa.Column('color_background', sa.String(length=20), nullable=True),
    sa.Column('color_text', sa.String(length=20), nullable=True),
    sa.Column('color_surface', sa.String(length=20), nullable=True),
    sa.Column('color_heading', sa.String(length=20), nullable=True),
    sa.Column('color_border', sa.String(length=20), nullable=True),
    sa.Column('color_muted', sa.String(length=20), nullable=True),
    sa.Column('color_dark', sa.String(length=20), nullable=True),
    sa.Column('color_light', sa.String(length=20), nullable=True),
    sa.Column('color_success', sa.String(length=20), nullable=True),
    sa.Column('color_warning', sa.String(length=20), nullable=True),
    sa.Column('color_danger', sa.String(length=20), nullable=True),
    sa.Column('color_info', sa.String(length=20), nullable=True),
    sa.Column('color_computed_data', sa.JSON(), nullable=True),
    sa.Column('color_contrast_ratios', sa.JSON(), nullable=True),
    sa.Column('color_wcag_compliance', sa.JSON(), nullable=True),
    sa.Column('color_poor_combinations', sa.JSON(), nullable=True),
    sa.Column('color_accessibility_score', sa.Float(), nullable=True),
    sa.Column('fonts', sa.JSON(), nullable=True),
    sa.Column('heading_h1', sa.String(length=100), nullable=True),
    sa.Column('heading_h2', sa.String(length=100), nullable=True),
    sa.Column('heading_h3', sa.String(length=100), nullable=True),
    sa.Column('body_font', sa.String(length=100), nullable=True),
    sa.Column('typography_primary_font', sa.String(length=200), nullable=True),
    sa.Column('typography_heading_font', sa.String(length=200), nullable=True),
    sa.Column('typography_secondary_font', sa.String(length=200), nullable=True),
    sa.Column('typography_fallback_stack', sa.JSON(), nullable=True),
    sa.Column('typography_is_google_font', sa.Boolean(), nullable=False),
    sa.Column('typography_is_system_font', sa.Boolean(), nullable=False),
    sa.Column('typography_weights_used', sa.JSON(), nullable=True),
    sa.Column('typography_hierarchy', sa.JSON(), nullable=True),
    sa.Column('design_language_name', sa.String(length=50), nullable=True),
    sa.Column('design_language_confidence', sa.Float(), nullable=True),
    sa.Column('design_language_all_scores', sa.JSON(), nullable=True),
    sa.Column('brand_personality_traits', sa.JSON(), nullable=True),
    sa.Column('brand_personality_scores', sa.JSON(), nullable=True),
    sa.Column('consistency_overall_score', sa.Float(), nullable=True),
    sa.Column('consistency_color_score', sa.Float(), nullable=True),
    sa.Column('consistency_spacing_score', sa.Float(), nullable=True),
    sa.Column('consistency_typography_score', sa.Float(), nullable=True),
    sa.Column('consistency_button_score', sa.Float(), nullable=True),
    sa.Column('consistency_card_score', sa.Float(), nullable=True),
    sa.Column('consistency_border_radius_score', sa.Float(), nullable=True),
    sa.Column('consistency_shadow_score', sa.Float(), nullable=True),
    sa.Column('consistency_component_counts', sa.JSON(), nullable=True),
    sa.Column('consistency_skipped_components', sa.JSON(), nullable=True),
    sa.Column('component_styles', sa.JSON(), nullable=True),
    sa.Column('navigation_items', sa.JSON(), nullable=True),
    sa.Column('navigation_logo', sa.String(length=500), nullable=True),
    sa.Column('is_sticky_nav', sa.Boolean(), nullable=False),
    sa.Column('nav_primary_items', sa.JSON(), nullable=True),
    sa.Column('nav_secondary_items', sa.JSON(), nullable=True),
    sa.Column('nav_footer_items', sa.JSON(), nullable=True),
    sa.Column('nav_depth', sa.Integer(), nullable=True),
    sa.Column('hero_title', sa.String(length=500), nullable=True),
    sa.Column('hero_subtitle', sa.String(length=1000), nullable=True),
    sa.Column('hero_cta_buttons', sa.JSON(), nullable=True),
    sa.Column('hero_background_image', sa.String(length=500), nullable=True),
    sa.Column('hero_description', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(length=500), nullable=True),
    sa.Column('hero_primary_cta', sa.JSON(), nullable=True),
    sa.Column('hero_secondary_cta', sa.JSON(), nullable=True),
    sa.Column('hero_background_image_url', sa.String(length=500), nullable=True),
    sa.Column('hero_background_color', sa.String(length=50), nullable=True),
    sa.Column('hero_layout', sa.String(length=50), nullable=True),
    sa.Column('hero_alignment', sa.String(length=20), nullable=True),
    sa.Column('hero_height', sa.Integer(), nullable=True),
    sa.Column('is_fallback_detection', sa.Boolean(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('ctas', sa.JSON(), nullable=True),
    sa.Column('footer_logo', sa.String(length=500), nullable=True),
    sa.Column('footer_description', sa.Text(), nullable=True),
    sa.Column('footer_links', sa.JSON(), nullable=True),
    sa.Column('footer_contact_emails', sa.JSON(), nullable=True),
    sa.Column('footer_contact_phones', sa.JSON(), nullable=True),
    sa.Column('footer_contact_address', sa.String(length=500), nullable=True),
    sa.Column('footer_social_links', sa.JSON(), nullable=True),
    sa.Column('footer_copyright', sa.String(length=500), nullable=True),
    sa.Column('footer_newsletter_signup', sa.Boolean(), nullable=False),
    sa.Column('footer_newsletter_action', sa.String(length=500), nullable=True),
    sa.Column('footer_is_fallback', sa.Boolean(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('contact_emails', sa.JSON(), nullable=True),
    sa.Column('contact_phones', sa.JSON(), nullable=True),
    sa.Column('contact_address', sa.Text(), nullable=True),
    sa.Column('contact_form_present', sa.Boolean(), nullable=False),
    sa.Column('contact_form_fields', sa.JSON(), nullable=True),
    sa.Column('contact_map_coordinates', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('testimonials', sa.JSON(), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('team_members', sa.JSON(), nullable=True),
    sa.Column('company_info', sa.JSON(), nullable=True),
    sa.Column('trust_signals', sa.JSON(), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('blog_links', sa.JSON(), nullable=True),
    sa.Column('social_links_present', sa.JSON(), nullable=True),
    sa.Column('seo_page_title', sa.String(length=500), nullable=True),
    sa.Column('seo_meta_description', sa.String(length=1000), nullable=True),
    sa.Column('seo_focus_keywords', sa.JSON(), nullable=True),
    sa.Column('seo_missing_meta_description', sa.Boolean(), nullable=False),
    sa.Column('seo_missing_title', sa.Boolean(), nullable=False),
    sa.Column('seo_missing_h1', sa.Boolean(), nullable=False),
    sa.Column('seo_https_enabled', sa.Boolean(), nullable=False),
    sa.Column('seo_ssl_status', sa.Boolean(), nullable=False),
    sa.Column('call_to_actions', sa.JSON(), nullable=True),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('website_blueprint', sa.JSON(), nullable=True),
    sa.Column('raw_html_size_kb', sa.Float(), nullable=True),
    sa.Column('extraction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_intelligence_id'), 'website_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_website_intelligence_lead_id'), 'website_intelligence', ['lead_id'], unique=True)


def downgrade() -> None:
    """Drop website_intelligence table."""
    op.drop_index(op.f('ix_website_intelligence_lead_id'), table_name='website_intelligence')
    op.drop_index(op.f('ix_website_intelligence_id'), table_name='website_intelligence')
    op.drop_table('website_intelligence')
