"""Add GenerationJob

Revision ID: 1ca584b0146f
Revises: f8a1b2c3d4e5
Create Date: 2026-07-09 17:10:20.961750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca584b0146f'
down_revision: Union[str, Sequence[str], None] = 'f8a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.String(length=255), nullable=False),
    sa.Column('website_id', sa.String(length=64), nullable=True),
    sa.Column('generation_id', sa.String(length=64), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('preview_path', sa.String(length=255), nullable=True),
    sa.Column('package_id', sa.String(length=64), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('generation_time', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_jobs_active_per_lead', 'generation_jobs', ['lead_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_job_id'), 'generation_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_generation_jobs_lead_id'), 'generation_jobs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_user_id'), 'generation_jobs', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_jobs_user_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_lead_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_job_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_active_per_lead', table_name='generation_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
