"""add_settings_and_profile_fields

Revision ID: 447b08563f58
Revises: d6f9e5d02c34
Create Date: 2026-06-28 13:27:57.888846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447b08563f58'
down_revision: Union[str, Sequence[str], None] = 'd6f9e5d02c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('theme', sa.String(length=20), nullable=False, server_default='system'))
    op.add_column('user_settings', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user_settings', sa.Column('default_page_size', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('user_settings', sa.Column('default_sorting', sa.String(length=50), nullable=False, server_default='created_at_desc'))
    op.add_column('user_settings', sa.Column('language', sa.String(length=20), nullable=False, server_default='en'))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=2083), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=100), nullable=True, server_default='UTC'))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'company_name')
    op.drop_column('user_settings', 'language')
    op.drop_column('user_settings', 'default_sorting')
    op.drop_column('user_settings', 'default_page_size')
    op.drop_column('user_settings', 'email_notifications')
    op.drop_column('user_settings', 'theme')
    # ### end Alembic commands ###
