from typing import Dict, List, Optional

STANDARD_SECTIONS: List[str] = [
    "navigation",
    "hero",
    "about",
    "services",
    "features",
    "why_choose_us",
    "portfolio",
    "testimonials",
    "pricing",
    "faq",
    "team",
    "contact",
    "footer",
]

SECTION_PRIORITIES: Dict[str, int] = {
    "hero": 1,
    "navigation": 2,
    "services": 3,
    "about": 4,
    "features": 5,
    "why_choose_us": 6,
    "portfolio": 7,
    "testimonials": 8,
    "pricing": 9,
    "faq": 10,
    "team": 11,
    "contact": 12,
    "footer": 13,
}

RECOMMENDED_SECTION_REASONS: Dict[str, str] = {
    "hero": "First impression and value proposition",
    "services": "Core offering showcase for lead conversion",
    "about": "Company story builds trust and connection",
    "features": "Highlights key differentiators",
    "why_choose_us": "Persuades visitors with unique advantages",
    "portfolio": "Visual proof of work and expertise",
    "testimonials": "Social proof increases conversion rates",
    "pricing": "Transparent pricing reduces friction",
    "faq": "Addresses common objections pre-sale",
    "team": "Personalizes the brand with real people",
    "contact": "Lead capture and inquiry channel",
}

LAYOUT_RECOMMENDATIONS: Dict[str, Dict[str, str]] = {
    "hero": {"layout": "full-width", "columns": "1", "alignment": "center"},
    "services": {"layout": "grid", "columns": "3", "alignment": "center"},
    "about": {"layout": "two-column", "columns": "2", "alignment": "left"},
    "features": {"layout": "grid", "columns": "3", "alignment": "center"},
    "why_choose_us": {"layout": "grid", "columns": "2", "alignment": "center"},
    "portfolio": {"layout": "grid", "columns": "3", "alignment": "center"},
    "testimonials": {"layout": "carousel", "columns": "1", "alignment": "center"},
    "pricing": {"layout": "grid", "columns": "3", "alignment": "center"},
    "faq": {"layout": "single-column", "columns": "1", "alignment": "left"},
    "team": {"layout": "grid", "columns": "4", "alignment": "center"},
    "contact": {"layout": "two-column", "columns": "2", "alignment": "left"},
}

ANIMATION_SUGGESTIONS: Dict[str, List[Dict[str, str]]] = {
    "hero": [
        {"element": "Headline", "animation": "fade-in-up", "duration": "600ms", "delay": "0ms"},
        {"element": "Subtitle", "animation": "fade-in-up", "duration": "600ms", "delay": "200ms"},
        {"element": "CTA Button", "animation": "fade-in-up", "duration": "600ms", "delay": "400ms"},
    ],
    "services": [
        {"element": "Section heading", "animation": "fade-in-up", "duration": "600ms", "delay": "0ms"},
        {"element": "Service cards", "animation": "stagger-fade-in", "duration": "400ms", "delay": "100ms"},
    ],
    "about": [
        {"element": "Image", "animation": "fade-in-left", "duration": "600ms", "delay": "0ms"},
        {"element": "Text content", "animation": "fade-in-right", "duration": "600ms", "delay": "100ms"},
    ],
    "testimonials": [
        {"element": "Testimonial cards", "animation": "fade-in", "duration": "500ms", "delay": "0ms"},
    ],
    "portfolio": [
        {"element": "Project cards", "animation": "stagger-fade-in", "duration": "400ms", "delay": "100ms"},
    ],
    "pricing": [
        {"element": "Plan cards", "animation": "fade-in-up", "duration": "500ms", "delay": "100ms"},
        {"element": "Popular badge", "animation": "pulse", "duration": "2s", "delay": "0ms"},
    ],
    "faq": [
        {"element": "Accordion items", "animation": "slide-down", "duration": "300ms", "delay": "0ms"},
    ],
    "team": [
        {"element": "Member cards", "animation": "stagger-fade-in", "duration": "400ms", "delay": "100ms"},
    ],
    "contact": [
        {"element": "Form", "animation": "fade-in-up", "duration": "500ms", "delay": "0ms"},
    ],
}

COMPONENT_REQUIREMENTS: Dict[str, List[str]] = {
    "navigation": ["Navbar", "MobileMenu", "NavLink", "CtaButton"],
    "hero": ["HeroSection", "CtaButton", "BackgroundImage", "Headline"],
    "services": ["ServiceCard", "IconBox", "SectionGrid", "SectionHeader"],
    "about": ["TwoColumnLayout", "ImageWithText", "StatsCounter", "MissionCard"],
    "features": ["FeatureCard", "IconList", "CheckList"],
    "why_choose_us": ["FeatureCard", "StatsCounter", "IconList"],
    "portfolio": ["PortfolioCard", "FilterTabs", "Lightbox", "MasonryGrid"],
    "testimonials": ["TestimonialCard", "Carousel", "StarRating", "Avatar"],
    "pricing": ["PricingCard", "ToggleSwitch", "FeatureList", "Badge"],
    "faq": ["Accordion", "SearchFilter", "Collapsible"],
    "team": ["TeamCard", "Avatar", "SocialIcon", "BioModal"],
    "contact": ["ContactForm", "MapEmbed", "ContactInfoCard", "SocialLinks"],
    "footer": ["Footer", "FooterColumn", "NewsletterForm", "SocialIcons"],
}

COLOR_SCHEMES: Dict[str, Dict[str, str]] = {
    "modern-saas-blue": {
        "primary": "#2563EB",
        "secondary": "#1E40AF",
        "accent": "#F59E0B",
        "background": "#FFFFFF",
        "surface": "#F8FAFC",
        "text": "#0F172A",
        "muted": "#64748B",
    },
    "modern-saas-green": {
        "primary": "#059669",
        "secondary": "#047857",
        "accent": "#F59E0B",
        "background": "#FFFFFF",
        "surface": "#F0FDF4",
        "text": "#052E16",
        "muted": "#6B7280",
    },
    "modern-saas-purple": {
        "primary": "#7C3AED",
        "secondary": "#5B21B6",
        "accent": "#FCD34D",
        "background": "#FFFFFF",
        "surface": "#F5F3FF",
        "text": "#1E1B4B",
        "muted": "#6B7280",
    },
    "dark-saas": {
        "primary": "#3B82F6",
        "secondary": "#1D4ED8",
        "accent": "#10B981",
        "background": "#0F172A",
        "surface": "#1E293B",
        "text": "#F8FAFC",
        "muted": "#94A3B8",
    },
    "minimal-light": {
        "primary": "#111827",
        "secondary": "#374151",
        "accent": "#3B82F6",
        "background": "#FFFFFF",
        "surface": "#F9FAFB",
        "text": "#111827",
        "muted": "#9CA3AF",
    },
}

WEBSITE_STYLES: List[str] = [
    "modern-saas",
    "enterprise-corporate",
    "startup-minimal",
    "creative-agency",
    "ecommerce",
    "saas-dark",
    "professional-service",
    "blog-content",
]

SECTION_IMAGE_REQUIREMENTS: Dict[str, str] = {
    "hero": "1920x1080 background or vector illustration",
    "services": "64x64 icons or 400x300 thumbnail per service",
    "about": "600x800 team/office photo",
    "portfolio": "1200x800 project screenshots (16:9)",
    "testimonials": "80x80 circular client headshots",
    "team": "400x400 team member headshots",
    "pricing": "48x48 icons per pricing tier",
    "contact": "Map embed or office photo",
}

INDUSTRY_RECOMMENDED_SECTIONS: Dict[str, List[str]] = {
    "restaurant": ["menu", "gallery", "reservations", "testimonials", "location"],
    "food": ["menu", "gallery", "reservations", "testimonials", "location"],
    "law": ["practice_areas", "attorneys", "consultation", "testimonials", "resources"],
    "legal": ["practice_areas", "attorneys", "consultation", "testimonials", "resources"],
    "agency": ["portfolio", "case_studies", "testimonials", "process", "clients"],
    "creative": ["portfolio", "case_studies", "testimonials", "process", "clients"],
    "saas": ["features", "pricing", "faq", "testimonials", "integrations"],
    "software": ["features", "pricing", "faq", "testimonials", "integrations", "documentation"],
    "tech": ["features", "pricing", "faq", "testimonials", "integrations"],
    "healthcare": ["doctors", "departments", "appointments", "testimonials", "insurance"],
    "medical": ["doctors", "departments", "appointments", "testimonials", "insurance"],
    "ecommerce": ["products", "categories", "cart", "testimonials", "shipping"],
    "retail": ["products", "categories", "cart", "testimonials", "shipping"],
    "education": ["courses", "instructors", "testimonials", "pricing", "faq"],
    "consulting": ["services", "case_studies", "resources", "testimonials", "contact"],
    "real_estate": ["properties", "gallery", "agents", "testimonials", "neighborhoods"],
    "fitness": ["classes", "trainers", "schedule", "pricing", "testimonials"],
    "gym": ["classes", "trainers", "schedule", "pricing", "testimonials"],
    "finance": ["services", "team", "testimonials", "resources", "contact"],
    "banking": ["services", "team", "testimonials", "resources", "contact"],
    "professional_services": ["services", "case_studies", "team", "testimonials", "resources"],
    "manufacturing": ["products", "services", "capabilities", "case_studies", "contact"],
    "nonprofit": ["mission", "programs", "impact", "donate", "volunteer"],
    "photography": ["portfolio", "gallery", "pricing", "testimonials", "booking"],
    "travel": ["destinations", "packages", "gallery", "testimonials", "booking"],
    "hospitality": ["rooms", "gallery", "amenities", "testimonials", "booking"],
    "automotive": ["inventory", "services", "gallery", "testimonials", "contact"],
    "construction": ["services", "projects", "gallery", "testimonials", "contact"],
}

HEADER_TYPES: List[str] = ["transparent", "solid", "sticky", "centered", "split", "sidebar"]

FOOTER_TYPES: Dict[str, Dict[str, Any]] = {
    "simple": {"columns": 2, "show_logo": False, "show_newsletter": False, "description": "Minimal copyright + links"},
    "business": {"columns": 3, "show_logo": True, "show_newsletter": False, "description": "Logo, contact, links, copyright"},
    "large-multi-column": {"columns": 4, "show_logo": True, "show_newsletter": True, "description": "Full footer with newsletter"},
    "minimal": {"columns": 1, "show_logo": False, "show_newsletter": False, "description": "Copyright only"},
}

SECTION_DISPLAY_NAMES: Dict[str, str] = {
    "navigation": "Navigation",
    "hero": "Hero",
    "about": "About Us",
    "services": "Our Services",
    "features": "Key Features",
    "why_choose_us": "Why Choose Us",
    "portfolio": "Portfolio",
    "case_studies": "Case Studies",
    "pricing": "Pricing",
    "testimonials": "Testimonials",
    "faq": "FAQ",
    "team": "Our Team",
    "blog": "Blog",
    "contact": "Contact Us",
    "footer": "Footer",
}

COMPONENT_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "Navbar": {
        "type": "navigation",
        "variants": ["default", "transparent", "solid", "sticky", "centered", "split", "sidebar"],
        "layouts": ["full-width", "container"],
        "sizes": ["compact", "medium", "large"],
        "description": "Top navigation bar with logo, links and optional CTA",
    },
    "Logo": {
        "type": "navigation",
        "variants": ["image", "text", "icon-text"],
        "layouts": ["left", "center"],
        "sizes": ["small", "medium", "large"],
        "description": "Brand logo displayed in navbar and footer",
    },
    "NavigationLink": {
        "type": "navigation",
        "variants": ["text", "underline", "pill", "highlight"],
        "layouts": ["horizontal", "vertical"],
        "sizes": ["small", "medium"],
        "description": "Single navigation link item",
    },
    "Dropdown": {
        "type": "navigation",
        "variants": ["hover", "click", "mega"],
        "layouts": ["dropdown", "flyout", "mega-menu"],
        "sizes": ["medium", "large"],
        "description": "Dropdown menu with nested navigation items",
    },
    "MegaMenu": {
        "type": "navigation",
        "variants": ["columns", "grid", "tabs"],
        "layouts": ["full-width", "container"],
        "sizes": ["large"],
        "description": "Large dropdown menu with multiple columns",
    },
    "Button": {
        "type": "global",
        "variants": ["primary", "secondary", "outline", "ghost", "cta"],
        "layouts": ["inline", "block", "icon-left", "icon-right"],
        "sizes": ["small", "medium", "large"],
        "description": "Clickable button element",
    },
    "HeroSection": {
        "type": "hero",
        "variants": ["centered", "split", "image-left", "image-right", "video-background", "minimal"],
        "layouts": ["full-width", "container", "split"],
        "sizes": ["medium", "large", "fullscreen"],
        "description": "Main hero banner section",
    },
    "HeroImage": {
        "type": "hero",
        "variants": ["background", "right-side", "left-side", "mockup", "illustration"],
        "layouts": ["cover", "contain", "inline"],
        "sizes": ["medium", "large", "full"],
        "description": "Hero section image or illustration",
    },
    "HeroVideo": {
        "type": "hero",
        "variants": ["background", "inline", "popup"],
        "layouts": ["cover", "contain"],
        "sizes": ["medium", "large", "fullscreen"],
        "description": "Hero section video background or embed",
    },
    "HeroCTA": {
        "type": "hero",
        "variants": ["dual-button", "single-button", "with-form", "with-video"],
        "layouts": ["stacked", "inline", "centered"],
        "sizes": ["medium", "large"],
        "description": "Call-to-action group in hero section",
    },
    "SectionHeader": {
        "type": "global",
        "variants": ["centered", "left-aligned", "with-decoration"],
        "layouts": ["single-column", "split"],
        "sizes": ["compact", "medium"],
        "description": "Section heading with optional subheading",
    },
    "ServiceCard": {
        "type": "services",
        "variants": ["icon-top", "icon-left", "image-card", "minimal", "detailed"],
        "layouts": ["grid", "carousel", "list"],
        "sizes": ["small", "medium", "large"],
        "description": "Individual service offering card",
    },
    "FeatureCard": {
        "type": "features",
        "variants": ["icon-top", "icon-left", "checklist", "numbered", "image-card"],
        "layouts": ["grid", "list", "alternating"],
        "sizes": ["small", "medium"],
        "description": "Feature highlight card",
    },
    "ProductCard": {
        "type": "products",
        "variants": ["simple", "detailed", "with-cta", "horizontal"],
        "layouts": ["grid", "carousel", "list"],
        "sizes": ["medium", "large"],
        "description": "Product showcase card",
    },
    "PricingCard": {
        "type": "pricing",
        "variants": ["simple", "featured", "comparison", "toggle"],
        "layouts": ["grid", "comparison-table"],
        "sizes": ["medium", "large"],
        "description": "Pricing plan card with feature list",
    },
    "PortfolioCard": {
        "type": "portfolio",
        "variants": ["image-top", "overlay", "masonry", "detailed"],
        "layouts": ["grid", "masonry", "carousel"],
        "sizes": ["small", "medium", "large"],
        "description": "Portfolio project card",
    },
    "CaseStudyCard": {
        "type": "portfolio",
        "variants": ["detailed", "minimal", "with-results", "horizontal"],
        "layouts": ["grid", "list", "carousel"],
        "sizes": ["medium", "large"],
        "description": "Case study or client success story card",
    },
    "GalleryGrid": {
        "type": "portfolio",
        "variants": ["grid", "masonry", "slider", "lightbox"],
        "layouts": ["grid", "masonry", "carousel"],
        "sizes": ["medium", "large", "full"],
        "description": "Image gallery grid with lightbox",
    },
    "StatisticCard": {
        "type": "statistics",
        "variants": ["counter", "simple", "with-icon", "with-label"],
        "layouts": ["grid", "inline", "row"],
        "sizes": ["small", "medium"],
        "description": "Statistical number display card",
    },
    "Timeline": {
        "type": "about",
        "variants": ["vertical", "horizontal", "alternating"],
        "layouts": ["single-column", "two-column"],
        "sizes": ["medium", "large"],
        "description": "Company history or process timeline",
    },
    "TeamCard": {
        "type": "team",
        "variants": ["photo-top", "photo-left", "minimal", "detailed", "carousel"],
        "layouts": ["grid", "carousel", "list"],
        "sizes": ["small", "medium", "large"],
        "description": "Team member profile card",
    },
    "TestimonialCard": {
        "type": "testimonials",
        "variants": ["quote", "card", "minimal", "detailed", "video"],
        "layouts": ["grid", "carousel", "single", "masonry"],
        "sizes": ["small", "medium", "large"],
        "description": "Client testimonial or review card",
    },
    "FAQAccordion": {
        "type": "faq",
        "variants": ["accordion", "list", "tabs", "searchable"],
        "layouts": ["single-column", "two-column", "full-width"],
        "sizes": ["medium", "large"],
        "description": "FAQ accordion or expandable list",
    },
    "ContactForm": {
        "type": "contact",
        "variants": ["simple", "detailed", "multi-step", "popup"],
        "layouts": ["single-column", "two-column"],
        "sizes": ["medium", "large"],
        "description": "Contact inquiry form",
    },
    "NewsletterForm": {
        "type": "footer",
        "variants": ["inline", "stacked", "modal", "bar"],
        "layouts": ["single-row", "stacked"],
        "sizes": ["compact", "medium"],
        "description": "Email newsletter signup form",
    },
    "GoogleMap": {
        "type": "contact",
        "variants": ["static", "interactive", "dark"],
        "layouts": ["full-width", "container", "card"],
        "sizes": ["medium", "large", "full"],
        "description": "Embedded Google Map",
    },
    "SocialIcons": {
        "type": "global",
        "variants": ["colored", "monochrome", "circle", "square", "with-labels"],
        "layouts": ["row", "grid", "inline"],
        "sizes": ["small", "medium"],
        "description": "Social media icon links",
    },
    "BlogCard": {
        "type": "blog",
        "variants": ["image-top", "minimal", "horizontal", "featured"],
        "layouts": ["grid", "list", "carousel"],
        "sizes": ["small", "medium", "large"],
        "description": "Blog post preview card",
    },
    "FooterColumns": {
        "type": "footer",
        "variants": ["2-columns", "3-columns", "4-columns", "5-columns"],
        "layouts": ["multi-column", "grid", "flex"],
        "sizes": ["medium", "large"],
        "description": "Footer column structure with link groups",
    },
    "Copyright": {
        "type": "footer",
        "variants": ["simple", "with-links", "with-social"],
        "layouts": ["centered", "split"],
        "sizes": ["compact"],
        "description": "Copyright notice bar",
    },
    "Divider": {
        "type": "global",
        "variants": ["line", "dashed", "dotted", "with-icon", "with-text"],
        "layouts": ["full-width", "container"],
        "sizes": ["compact"],
        "description": "Visual divider between sections",
    },
    "Badge": {
        "type": "global",
        "variants": ["default", "pill", "icon", "outline", "dot"],
        "layouts": ["inline", "stacked"],
        "sizes": ["small", "medium"],
        "description": "Status or label badge",
    },
    "Tag": {
        "type": "global",
        "variants": ["default", "outline", "colored", "removable", "link"],
        "layouts": ["inline", "wrap", "scroll"],
        "sizes": ["small", "medium"],
        "description": "Content tag or category label",
    },
    "TrustBadge": {
        "type": "trust",
        "variants": ["logo", "certification", "seal", "partner", "award", "guarantee"],
        "layouts": ["row", "grid", "carousel"],
        "sizes": ["small", "medium"],
        "description": "Trust, certification, or partner badge",
    },
    "IconBox": {
        "type": "global",
        "variants": ["circle", "square", "rounded", "outline", "colored", "ghost"],
        "layouts": ["inline", "centered", "left"],
        "sizes": ["small", "medium", "large"],
        "description": "Icon container with optional background",
    },
    "ImageWithText": {
        "type": "about",
        "variants": ["image-left", "image-right", "image-top", "overlap", "split"],
        "layouts": ["two-column", "stacked", "overlap"],
        "sizes": ["medium", "large"],
        "description": "Image and text content in a two-column layout",
    },
    "StatsCounter": {
        "type": "statistics",
        "variants": ["simple", "with-icon", "with-label", "animated"],
        "layouts": ["grid", "inline", "row"],
        "sizes": ["small", "medium"],
        "description": "Animated statistics counter",
    },
    "FilterTabs": {
        "type": "portfolio",
        "variants": ["underline", "pill", "dropdown", "buttons"],
        "layouts": ["row", "wrap", "scroll"],
        "sizes": ["small", "medium"],
        "description": "Category filter tabs or buttons",
    },
    "Lightbox": {
        "type": "portfolio",
        "variants": ["modal", "inline", "fullscreen", "gallery"],
        "layouts": ["overlay", "fullscreen"],
        "sizes": ["full"],
        "description": "Image lightbox or modal viewer",
    },
    "Accordion": {
        "type": "faq",
        "variants": ["single", "multiple", "nested"],
        "layouts": ["single-column", "two-column"],
        "sizes": ["medium", "large"],
        "description": "Expandable accordion panel",
    },
    "Carousel": {
        "type": "global",
        "variants": ["fade", "slide", "coverflow", "cards"],
        "layouts": ["single", "multi-item", "centered"],
        "sizes": ["medium", "large", "full"],
        "description": "Content carousel or slider",
    },
    "StarRating": {
        "type": "testimonials",
        "variants": ["stars", "numbers", "icons", "color-coded"],
        "layouts": ["inline", "stacked"],
        "sizes": ["small", "medium"],
        "description": "Star rating display",
    },
    "Avatar": {
        "type": "global",
        "variants": ["circle", "square", "rounded", "with-border"],
        "layouts": ["inline", "stacked", "group"],
        "sizes": ["xsmall", "small", "medium", "large"],
        "description": "User avatar or profile photo",
    },
    "BioModal": {
        "type": "team",
        "variants": ["modal", "drawer", "expandable", "tooltip"],
        "layouts": ["overlay", "side-panel", "inline"],
        "sizes": ["medium", "large"],
        "description": "Team member biography modal",
    },
    "ContactInfoCard": {
        "type": "contact",
        "variants": ["icon-list", "card-grid", "inline", "detailed"],
        "layouts": ["grid", "list", "inline"],
        "sizes": ["small", "medium"],
        "description": "Contact information display card",
    },
    "MapEmbed": {
        "type": "contact",
        "variants": ["static", "interactive", "satellite"],
        "layouts": ["full-width", "container", "card"],
        "sizes": ["medium", "large", "full"],
        "description": "Embedded map location",
    },
    "CheckList": {
        "type": "features",
        "variants": ["icon", "checkbox", "numbered", "bullet"],
        "layouts": ["single-column", "two-column", "grid"],
        "sizes": ["small", "medium"],
        "description": "Feature checklist with icons",
    },
    "MasonryGrid": {
        "type": "portfolio",
        "variants": ["columns", "rows", "packed"],
        "layouts": ["masonry", "grid"],
        "sizes": ["medium", "large", "full"],
        "description": "Masonry layout grid",
    },
}

COMPONENT_LAYOUT_OPTIONS: Dict[str, List[str]] = {
    "1-column": ["single-column", "stacked", "centered"],
    "2-column": ["two-column", "split", "grid-2"],
    "3-column": ["grid-3", "three-column"],
    "4-column": ["grid-4", "four-column"],
    "responsive-grid": ["grid", "auto-fill", "auto-fit"],
    "carousel": ["carousel", "slider", "swiper"],
    "stack": ["stacked", "vertical", "list"],
    "split": ["split", "side-by-side", "alternating"],
    "full-width": ["full-width", "full-screen", "edge-to-edge"],
    "container": ["boxed", "contained", "centered"],
}

# ──────────────────────────────────────────────
# Phase 2.7d — Theme & Animation Blueprint
# ──────────────────────────────────────────────

VISUAL_STYLES: Dict[str, str] = {
    "modern-saas": "Clean, functional, data-driven with vibrant primary colors and ample whitespace",
    "corporate": "Trustworthy, professional, restrained color palette, sharp typography, conservative spacing",
    "creative-agency": "Expressive, bold, experimental layouts, vibrant gradients, large typography",
    "minimal": "Ultra-clean, maximum whitespace, monochrome palette, sparse content, high elegance",
    "luxury": "Rich, sophisticated, dark gold/black palette, serif typography, premium feel",
    "medical": "Clean, sterile, calming blues and greens, rounded corners, high readability",
    "restaurant": "Warm, appetizing, earthy tones, rich imagery, large food photography",
    "portfolio": "Gallery-forward, minimal chrome, full-bleed imagery, subtle typography",
    "startup": "Bold, energetic, gradient-heavy, large headlines, playful accents, high contrast",
    "professional-service": "Trustworthy, approachable, clean blues, clear hierarchy, structured layout",
    "friendly": "Warm, approachable, rounded elements, soft colors, playful illustrations",
    "elegant": "Refined, sophisticated, muted palette, serif headings, refined spacing",
    "technology": "Futuristic, dark mode, neon accents, grid layouts, tech-forward typography",
}

UI_PERSONALITIES: Dict[str, str] = {
    "minimal": "Less is more. Maximum whitespace, minimal decoration, focus on content",
    "bold": "Confident, large elements, high contrast, oversized typography, vibrant colors",
    "clean": "Organized, structured, consistent spacing, clear hierarchy, professional",
    "premium": "Refined, detailed, subtle animations, rich textures, high-end feel",
    "playful": "Fun, colorful, rounded elements, whimsical illustrations, loose spacing",
    "serious": "Professional, formal, restrained palette, structured, conservative design",
    "elegant": "Sophisticated, graceful, refined typography, muted tones, balanced composition",
    "corporate": "Business-focused, structured, blue-centric, conservative, trustworthy",
}

BUTTON_STYLES: List[str] = [
    "rounded-full", "rounded-lg", "rounded-md", "pill", "square",
    "outline", "ghost", "soft", "gradient", "shadow",
]

CARD_STYLES: List[str] = [
    "elevated", "bordered", "flat", "glassmorphism", "neumorphic",
    "outline", "gradient-border", "soft-shadow",
]

FORM_STYLES: List[str] = [
    "standard", "underlined", "filled", "outlined", "soft",
    "floating-label", "material",
]

ICON_STYLES: List[str] = [
    "outline", "solid", "duotone", "rounded", "square",
    "colored-bg", "ghost", "gradient",
]

SPACING_SCALES: Dict[str, Dict[str, str]] = {
    "compact": {"section": "48px", "element": "16px", "grid": "12px"},
    "default": {"section": "80px", "element": "24px", "grid": "24px"},
    "spacious": {"section": "120px", "element": "32px", "grid": "32px"},
    "generous": {"section": "160px", "element": "48px", "grid": "40px"},
}

CONTAINER_WIDTHS: Dict[str, str] = {
    "narrow": "960px",
    "default": "1200px",
    "wide": "1320px",
    "full": "100%",
}

ANIMATION_TYPES: List[str] = [
    "fade", "fade-in-up", "fade-in-down", "fade-in-left", "fade-in-right",
    "slide-up", "slide-down", "slide-left", "slide-right",
    "scale", "scale-up", "scale-down",
    "stagger", "stagger-fade-in",
    "parallax",
    "hover-lift", "hover-scale",
    "button-ripple",
    "card-hover",
    "image-zoom",
    "counter-animation",
    "progress-reveal",
    "accordion",
    "modal", "drawer",
]

ANIMATION_TRIGGERS: List[str] = [
    "on-load", "on-scroll", "on-hover", "on-click", "on-focus",
]

ANIMATION_PRIORITIES: List[str] = [
    "low", "medium", "high", "critical",
]

ANIMATION_LEVELS: Dict[str, int] = {
    "low": 0,
    "medium": 1,
    "high": 2,
}

ANIMATION_EASING_OPTIONS: Dict[str, str] = {
    "ease": "cubic-bezier(0.25, 0.1, 0.25, 1.0)",
    "ease-in": "cubic-bezier(0.42, 0.0, 1.0, 1.0)",
    "ease-out": "cubic-bezier(0.0, 0.0, 0.58, 1.0)",
    "ease-in-out": "cubic-bezier(0.42, 0.0, 0.58, 1.0)",
    "spring": "cubic-bezier(0.175, 0.885, 0.32, 1.275)",
    "bounce": "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
    "smooth": "cubic-bezier(0.645, 0.045, 0.355, 1.0)",
    "snappy": "cubic-bezier(0.4, 0.0, 0.2, 1.0)",
}

VISUAL_STYLE_ANIMATION_LEVEL_MAP: Dict[str, str] = {
    "modern-saas": "medium",
    "corporate": "low",
    "creative-agency": "high",
    "minimal": "low",
    "luxury": "medium",
    "medical": "low",
    "restaurant": "medium",
    "portfolio": "medium",
    "startup": "high",
    "professional-service": "low",
    "friendly": "high",
    "elegant": "medium",
    "technology": "high",
}

INDUSTRY_VISUAL_STYLE_MAP: Dict[str, str] = {
    "restaurant": "restaurant",
    "food": "restaurant",
    "bakery": "restaurant",
    "cafe": "restaurant",
    "law": "professional-service",
    "legal": "professional-service",
    "agency": "creative-agency",
    "creative": "creative-agency",
    "design": "creative-agency",
    "art": "creative-agency",
    "photography": "portfolio",
    "videography": "portfolio",
    "saas": "modern-saas",
    "software": "technology",
    "tech": "technology",
    "startup": "startup",
    "healthcare": "medical",
    "medical": "medical",
    "hospital": "medical",
    "clinic": "medical",
    "ecommerce": "modern-saas",
    "retail": "modern-saas",
    "education": "professional-service",
    "consulting": "professional-service",
    "real_estate": "professional-service",
    "fitness": "friendly",
    "gym": "friendly",
    "finance": "corporate",
    "banking": "corporate",
    "insurance": "corporate",
    "manufacturing": "corporate",
    "nonprofit": "friendly",
    "travel": "creative-agency",
    "hospitality": "luxury",
    "hotel": "luxury",
    "automotive": "modern-saas",
    "construction": "corporate",
    "professional_services": "professional-service",
}

INDUSTRY_UI_PERSONALITY_MAP: Dict[str, str] = {
    "restaurant": "playful",
    "food": "playful",
    "law": "serious",
    "legal": "serious",
    "agency": "bold",
    "creative": "bold",
    "saas": "clean",
    "software": "clean",
    "tech": "bold",
    "startup": "bold",
    "healthcare": "clean",
    "medical": "serious",
    "education": "clean",
    "consulting": "corporate",
    "real_estate": "premium",
    "fitness": "playful",
    "gym": "playful",
    "finance": "corporate",
    "banking": "serious",
    "manufacturing": "corporate",
    "nonprofit": "friendly",
    "travel": "playful",
    "hospitality": "premium",
    "hotel": "luxury",
    "automotive": "bold",
    "construction": "serious",
    "professional_services": "corporate",
    "photography": "elegant",
    "portfolio": "minimal",
    "ecommerce": "clean",
    "retail": "clean",
}

WEBSITE_STYLE_THEME_PRESETS: Dict[str, Dict[str, Any]] = {
    "modern-saas": {
        "visual_style": "modern-saas",
        "ui_personality": "clean",
        "button_style": "rounded-lg",
        "card_style": "elevated",
        "form_style": "standard",
        "icon_style": "outline",
        "spacing_scale": "default",
        "container_width": "default",
        "border_radius": "8px",
        "shadow": "0 1px 3px rgba(0,0,0,0.1)",
        "transition_duration": "200ms",
        "dark_mode": False,
    },
    "corporate": {
        "visual_style": "corporate",
        "ui_personality": "corporate",
        "button_style": "rounded-md",
        "card_style": "bordered",
        "form_style": "standard",
        "icon_style": "outline",
        "spacing_scale": "default",
        "container_width": "default",
        "border_radius": "4px",
        "shadow": "0 1px 2px rgba(0,0,0,0.05)",
        "transition_duration": "200ms",
        "dark_mode": False,
    },
    "creative-agency": {
        "visual_style": "creative-agency",
        "ui_personality": "bold",
        "button_style": "pill",
        "card_style": "glassmorphism",
        "form_style": "outlined",
        "icon_style": "duotone",
        "spacing_scale": "spacious",
        "container_width": "wide",
        "border_radius": "12px",
        "shadow": "0 8px 32px rgba(0,0,0,0.12)",
        "transition_duration": "300ms",
        "dark_mode": False,
    },
    "startup": {
        "visual_style": "startup",
        "ui_personality": "bold",
        "button_style": "rounded-full",
        "card_style": "soft-shadow",
        "form_style": "underlined",
        "icon_style": "solid",
        "spacing_scale": "generous",
        "container_width": "wide",
        "border_radius": "16px",
        "shadow": "0 4px 20px rgba(0,0,0,0.08)",
        "transition_duration": "250ms",
        "dark_mode": False,
    },
    "luxury": {
        "visual_style": "luxury",
        "ui_personality": "elegant",
        "button_style": "shadow",
        "card_style": "gradient-border",
        "form_style": "floating-label",
        "icon_style": "rounded",
        "spacing_scale": "spacious",
        "container_width": "narrow",
        "border_radius": "4px",
        "shadow": "0 4px 24px rgba(0,0,0,0.15)",
        "transition_duration": "400ms",
        "dark_mode": False,
    },
    "medical": {
        "visual_style": "medical",
        "ui_personality": "serious",
        "button_style": "rounded-lg",
        "card_style": "flat",
        "form_style": "soft",
        "icon_style": "colored-bg",
        "spacing_scale": "default",
        "container_width": "default",
        "border_radius": "8px",
        "shadow": "0 1px 3px rgba(0,0,0,0.08)",
        "transition_duration": "200ms",
        "dark_mode": False,
    },
    "friendly": {
        "visual_style": "friendly",
        "ui_personality": "playful",
        "button_style": "rounded-full",
        "card_style": "soft-shadow",
        "form_style": "filled",
        "icon_style": "colored-bg",
        "spacing_scale": "spacious",
        "container_width": "default",
        "border_radius": "16px",
        "shadow": "0 4px 12px rgba(0,0,0,0.06)",
        "transition_duration": "250ms",
        "dark_mode": False,
    },
    "portfolio": {
        "visual_style": "portfolio",
        "ui_personality": "minimal",
        "button_style": "ghost",
        "card_style": "flat",
        "form_style": "standard",
        "icon_style": "outline",
        "spacing_scale": "spacious",
        "container_width": "wide",
        "border_radius": "0px",
        "shadow": "none",
        "transition_duration": "300ms",
        "dark_mode": False,
    },
    "professional-service": {
        "visual_style": "professional-service",
        "ui_personality": "corporate",
        "button_style": "rounded-md",
        "card_style": "elevated",
        "form_style": "standard",
        "icon_style": "outline",
        "spacing_scale": "default",
        "container_width": "default",
        "border_radius": "6px",
        "shadow": "0 1px 3px rgba(0,0,0,0.08)",
        "transition_duration": "200ms",
        "dark_mode": False,
    },
    "elegant": {
        "visual_style": "elegant",
        "ui_personality": "elegant",
        "button_style": "ghost",
        "card_style": "bordered",
        "form_style": "underlined",
        "icon_style": "rounded",
        "spacing_scale": "spacious",
        "container_width": "narrow",
        "border_radius": "2px",
        "shadow": "0 2px 8px rgba(0,0,0,0.04)",
        "transition_duration": "300ms",
        "dark_mode": False,
    },
    "technology": {
        "visual_style": "technology",
        "ui_personality": "bold",
        "button_style": "rounded-lg",
        "card_style": "glassmorphism",
        "form_style": "outlined",
        "icon_style": "solid",
        "spacing_scale": "default",
        "container_width": "wide",
        "border_radius": "8px",
        "shadow": "0 4px 16px rgba(0,0,0,0.1)",
        "transition_duration": "200ms",
        "dark_mode": True,
    },
}

COMPONENT_ANIMATION_DEFAULTS: Dict[str, Dict[str, Any]] = {
    "Navbar": {"animation_type": "slide-down", "duration_ms": 300, "delay_ms": 0, "easing": "ease-out", "trigger": "on-load", "priority": "critical"},
    "Logo": {"animation_type": "fade-in", "duration_ms": 400, "delay_ms": 100, "easing": "ease-out", "trigger": "on-load", "priority": "high"},
    "NavigationLink": {"animation_type": "fade-in-down", "duration_ms": 300, "delay_ms": 200, "easing": "ease-out", "trigger": "on-load", "priority": "medium"},
    "Button": {"animation_type": "fade-in-up", "duration_ms": 400, "delay_ms": 300, "easing": "ease-out", "trigger": "on-load", "priority": "medium"},
    "HeroSection": {"animation_type": "fade-in-up", "duration_ms": 600, "delay_ms": 0, "easing": "ease-out", "trigger": "on-load", "priority": "critical"},
    "HeroImage": {"animation_type": "scale", "duration_ms": 800, "delay_ms": 200, "easing": "ease-out", "trigger": "on-load", "priority": "high"},
    "HeroCTA": {"animation_type": "fade-in-up", "duration_ms": 500, "delay_ms": 400, "easing": "spring", "trigger": "on-load", "priority": "high"},
    "SectionHeader": {"animation_type": "fade-in-up", "duration_ms": 500, "delay_ms": 0, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "ServiceCard": {"animation_type": "stagger-fade-in", "duration_ms": 400, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "FeatureCard": {"animation_type": "stagger-fade-in", "duration_ms": 400, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "ProductCard": {"animation_type": "stagger-fade-in", "duration_ms": 400, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "PricingCard": {"animation_type": "fade-in-up", "duration_ms": 500, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "PortfolioCard": {"animation_type": "stagger-fade-in", "duration_ms": 400, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "TeamCard": {"animation_type": "stagger-fade-in", "duration_ms": 400, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "TestimonialCard": {"animation_type": "fade-in", "duration_ms": 500, "delay_ms": 0, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "FAQAccordion": {"animation_type": "accordion", "duration_ms": 300, "delay_ms": 0, "easing": "ease-in-out", "trigger": "on-click", "priority": "low"},
    "ContactForm": {"animation_type": "fade-in-up", "duration_ms": 500, "delay_ms": 0, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "StatsCounter": {"animation_type": "counter-animation", "duration_ms": 1500, "delay_ms": 200, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "Carousel": {"animation_type": "slide-left", "duration_ms": 400, "delay_ms": 0, "easing": "ease-in-out", "trigger": "on-click", "priority": "low"},
    "Accordion": {"animation_type": "accordion", "duration_ms": 300, "delay_ms": 0, "easing": "ease-in-out", "trigger": "on-click", "priority": "low"},
    "ImageWithText": {"animation_type": "fade-in-left", "duration_ms": 600, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "Lightbox": {"animation_type": "modal", "duration_ms": 300, "delay_ms": 0, "easing": "ease-out", "trigger": "on-click", "priority": "low"},
    "BioModal": {"animation_type": "modal", "duration_ms": 300, "delay_ms": 0, "easing": "ease-out", "trigger": "on-click", "priority": "low"},
    "GalleryGrid": {"animation_type": "stagger-fade-in", "duration_ms": 400, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "Timeline": {"animation_type": "slide-up", "duration_ms": 500, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "medium"},
    "MapEmbed": {"animation_type": "fade-in", "duration_ms": 500, "delay_ms": 0, "easing": "ease-out", "trigger": "on-scroll", "priority": "low"},
    "ContactInfoCard": {"animation_type": "fade-in-up", "duration_ms": 400, "delay_ms": 100, "easing": "ease-out", "trigger": "on-scroll", "priority": "low"},
    "FooterColumns": {"animation_type": "fade-in-up", "duration_ms": 400, "delay_ms": 0, "easing": "ease-out", "trigger": "on-load", "priority": "low"},
    "SocialIcons": {"animation_type": "fade-in", "duration_ms": 300, "delay_ms": 300, "easing": "ease-out", "trigger": "on-load", "priority": "low"},
    "Copyright": {"animation_type": "fade-in", "duration_ms": 300, "delay_ms": 500, "easing": "ease-out", "trigger": "on-load", "priority": "low"},
}

# ──────────────────────────────────────────────
# Phase 2.7e — SEO & Performance Blueprint
# ──────────────────────────────────────────────

SCHEMA_TYPE_MAP: Dict[str, List[str]] = {
    "restaurant": ["Restaurant", "LocalBusiness", "Organization", "Breadcrumb"],
    "food": ["Restaurant", "LocalBusiness", "Organization", "Breadcrumb"],
    "bakery": ["Restaurant", "LocalBusiness", "Organization", "Breadcrumb"],
    "cafe": ["Restaurant", "LocalBusiness", "Organization", "Breadcrumb"],
    "law": ["LegalService", "LocalBusiness", "Organization", "FAQ"],
    "legal": ["LegalService", "LocalBusiness", "Organization", "FAQ"],
    "law_firm": ["LegalService", "LocalBusiness", "Organization", "FAQ"],
    "attorney": ["LegalService", "LocalBusiness", "Organization", "FAQ"],
    "agency": ["Organization", "CreativeWork", "Review", "Breadcrumb"],
    "creative": ["Organization", "CreativeWork", "Review", "Breadcrumb"],
    "design": ["Organization", "CreativeWork", "Review", "Breadcrumb"],
    "photography": ["Organization", "ImageObject", "Review", "Breadcrumb"],
    "saas": ["SoftwareApplication", "Organization", "FAQ", "Review"],
    "software": ["SoftwareApplication", "Organization", "FAQ", "Review"],
    "tech": ["SoftwareApplication", "Organization", "FAQ", "Breadcrumb"],
    "startup": ["Organization", "SoftwareApplication", "FAQ", "Breadcrumb"],
    "healthcare": ["MedicalBusiness", "LocalBusiness", "Organization", "FAQ"],
    "medical": ["MedicalBusiness", "LocalBusiness", "Organization", "FAQ"],
    "hospital": ["MedicalBusiness", "LocalBusiness", "Organization", "FAQ"],
    "clinic": ["MedicalBusiness", "LocalBusiness", "Organization", "FAQ"],
    "ecommerce": ["Product", "Organization", "Breadcrumb", "Review"],
    "retail": ["Product", "Organization", "Breadcrumb", "Review"],
    "education": ["Organization", "Course", "Breadcrumb", "FAQ"],
    "consulting": ["Organization", "ProfessionalService", "Review", "FAQ"],
    "real_estate": ["Organization", "LocalBusiness", "Review", "Breadcrumb"],
    "fitness": ["LocalBusiness", "Organization", "Review", "Breadcrumb"],
    "gym": ["LocalBusiness", "Organization", "Review", "Breadcrumb"],
    "finance": ["Organization", "FinancialService", "FAQ", "Breadcrumb"],
    "banking": ["Organization", "FinancialService", "FAQ", "Breadcrumb"],
    "insurance": ["Organization", "InsuranceAgency", "FAQ", "Breadcrumb"],
    "manufacturing": ["Organization", "Product", "Breadcrumb", "Review"],
    "nonprofit": ["Organization", "NGO", "Article", "Breadcrumb"],
    "travel": ["Organization", "TravelAgency", "Review", "Breadcrumb"],
    "hospitality": ["Organization", "LocalBusiness", "Review", "Breadcrumb"],
    "hotel": ["Organization", "LocalBusiness", "Review", "Breadcrumb"],
    "automotive": ["Organization", "LocalBusiness", "Product", "FAQ"],
    "construction": ["Organization", "LocalBusiness", "Review", "Breadcrumb"],
    "professional_services": ["Organization", "ProfessionalService", "FAQ", "Breadcrumb"],
    "portfolio": ["Organization", "CreativeWork", "Review", "Breadcrumb"],
    "blog": ["Organization", "Article", "Breadcrumb", "Review"],
}

SCHEMA_ORG_NAMES: Dict[str, str] = {
    "restaurant": "Restaurant",
    "food": "Restaurant",
    "law": "LegalService",
    "legal": "LegalService",
    "healthcare": "MedicalBusiness",
    "medical": "MedicalBusiness",
    "hospital": "MedicalBusiness",
    "clinic": "MedicalBusiness",
    "ecommerce": "Store",
    "retail": "Store",
    "saas": "SoftwareApplication",
    "software": "SoftwareApplication",
    "tech": "Corporation",
    "agency": "Corporation",
    "creative": "Corporation",
    "consulting": "ProfessionalService",
    "real_estate": "RealEstateAgent",
    "finance": "FinancialService",
    "banking": "FinancialService",
    "insurance": "InsuranceAgency",
    "nonprofit": "NGO",
    "photography": "Photography",
    "travel": "TravelAgency",
    "hotel": "Hotel",
    "hospitality": "Hotel",
    "automotive": "AutoDealer",
    "construction": "HomeAndConstructionBusiness",
    "fitness": "HealthClub",
    "gym": "HealthClub",
    "education": "EducationalOrganization",
    "professional_services": "ProfessionalService",
    "blog": "Blog",
    "portfolio": "CreativeWork",
}

PERFORMANCE_TARGETS_BY_STYLE: Dict[str, Dict[str, Any]] = {
    "modern-saas": {
        "target_lighthouse_score": 90,
        "target_pagespeed_score": 85,
        "target_fcp": "1.8s",
        "target_lcp": "2.5s",
        "target_cls": 0.1,
        "target_tbt": "200ms",
        "target_inp": "200ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": False,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "corporate": {
        "target_lighthouse_score": 95,
        "target_pagespeed_score": 90,
        "target_fcp": "1.5s",
        "target_lcp": "2.2s",
        "target_cls": 0.08,
        "target_tbt": "150ms",
        "target_inp": "150ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": True,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "creative-agency": {
        "target_lighthouse_score": 85,
        "target_pagespeed_score": 80,
        "target_fcp": "2.0s",
        "target_lcp": "3.0s",
        "target_cls": 0.15,
        "target_tbt": "300ms",
        "target_inp": "250ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": False,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "startup": {
        "target_lighthouse_score": 85,
        "target_pagespeed_score": 80,
        "target_fcp": "2.0s",
        "target_lcp": "2.8s",
        "target_cls": 0.1,
        "target_tbt": "250ms",
        "target_inp": "200ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": False,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "luxury": {
        "target_lighthouse_score": 85,
        "target_pagespeed_score": 80,
        "target_fcp": "2.2s",
        "target_lcp": "3.0s",
        "target_cls": 0.12,
        "target_tbt": "300ms",
        "target_inp": "250ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": True,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "medical": {
        "target_lighthouse_score": 90,
        "target_pagespeed_score": 85,
        "target_fcp": "1.5s",
        "target_lcp": "2.2s",
        "target_cls": 0.08,
        "target_tbt": "150ms",
        "target_inp": "150ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": True,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "friendly": {
        "target_lighthouse_score": 90,
        "target_pagespeed_score": 85,
        "target_fcp": "1.8s",
        "target_lcp": "2.5s",
        "target_cls": 0.1,
        "target_tbt": "200ms",
        "target_inp": "200ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": False,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "portfolio": {
        "target_lighthouse_score": 90,
        "target_pagespeed_score": 85,
        "target_fcp": "1.5s",
        "target_lcp": "2.2s",
        "target_cls": 0.08,
        "target_tbt": "150ms",
        "target_inp": "150ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": True,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "professional-service": {
        "target_lighthouse_score": 95,
        "target_pagespeed_score": 90,
        "target_fcp": "1.5s",
        "target_lcp": "2.2s",
        "target_cls": 0.08,
        "target_tbt": "150ms",
        "target_inp": "150ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": True,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "elegant": {
        "target_lighthouse_score": 90,
        "target_pagespeed_score": 85,
        "target_fcp": "2.0s",
        "target_lcp": "2.8s",
        "target_cls": 0.1,
        "target_tbt": "200ms",
        "target_inp": "200ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "defer",
        "prefetch_required": False,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
    "technology": {
        "target_lighthouse_score": 85,
        "target_pagespeed_score": 80,
        "target_fcp": "2.0s",
        "target_lcp": "2.8s",
        "target_cls": 0.1,
        "target_tbt": "250ms",
        "target_inp": "200ms",
        "image_optimization": True,
        "code_splitting": True,
        "dynamic_imports": True,
        "font_preloading": True,
        "script_strategy": "async",
        "prefetch_required": True,
        "preconnect_required": True,
        "dns_prefetch_required": True,
    },
}

ACCESSIBILITY_TARGETS: Dict[str, Dict[str, Any]] = {
    "modern-saas": {"wcag_target": "AA", "color_contrast": True},
    "corporate": {"wcag_target": "AAA", "color_contrast": True},
    "creative-agency": {"wcag_target": "AA", "color_contrast": True},
    "startup": {"wcag_target": "AA", "color_contrast": True},
    "luxury": {"wcag_target": "AA", "color_contrast": True},
    "medical": {"wcag_target": "AAA", "color_contrast": True},
    "friendly": {"wcag_target": "AA", "color_contrast": True},
    "portfolio": {"wcag_target": "AA", "color_contrast": True},
    "professional-service": {"wcag_target": "AA", "color_contrast": True},
    "elegant": {"wcag_target": "AA", "color_contrast": True},
    "technology": {"wcag_target": "AA", "color_contrast": True},
}

SECTION_HEADING_SUGGESTIONS: Dict[str, Dict[str, Any]] = {
    "hero": {"h1": ["{brand_name}: {tagline}", "{brand_name} — {value_proposition}"], "h2": []},
    "about": {"h2": ["About {brand_name}", "Our Story", "Who We Are"], "h3": ["Our Mission", "Our Values", "Our Team"]},
    "services": {"h2": ["Our Services", "What We Offer", "How We Help"], "h3": ["Service Details", "Process"]},
    "features": {"h2": ["Key Features", "Why Choose Us", "What Sets Us Apart"], "h3": ["Feature Highlights"]},
    "why_choose_us": {"h2": ["Why {brand_name}", "Why Choose Us", "Our Advantage"], "h3": ["Key Differentiators"]},
    "portfolio": {"h2": ["Our Work", "Portfolio", "Recent Projects"], "h3": ["Project Details", "Case Study"]},
    "pricing": {"h2": ["Pricing Plans", "Choose Your Plan", "Simple Pricing"], "h3": ["Plan Features", "Add-ons"]},
    "testimonials": {"h2": ["What Our Clients Say", "Testimonials", "Client Feedback"], "h3": []},
    "faq": {"h2": ["Frequently Asked Questions", "FAQs", "Common Questions"], "h3": []},
    "team": {"h2": ["Meet Our Team", "Our People", "The Team"], "h3": ["Team Member Bio"]},
    "blog": {"h2": ["Latest Posts", "From Our Blog", "Articles & Insights"], "h3": ["Related Posts"]},
    "contact": {"h2": ["Get In Touch", "Contact Us", "Let's Talk"], "h3": []},
}

# ──────────────────────────────────────────────
# Phase 2.7f — Blueprint Finalization
# ──────────────────────────────────────────────

COMPLEXITY_LEVELS: Dict[str, Dict[str, Any]] = {
    "small": {
        "section_range": [1, 4],
        "component_range": [5, 20],
        "asset_count": [2, 5],
        "estimated_pages": 1,
        "estimated_ai_tokens": 2000,
    },
    "medium": {
        "section_range": [5, 8],
        "component_range": [21, 50],
        "asset_count": [6, 15],
        "estimated_pages": 3,
        "estimated_ai_tokens": 5000,
    },
    "large": {
        "section_range": [9, 12],
        "component_range": [51, 100],
        "asset_count": [16, 30],
        "estimated_pages": 5,
        "estimated_ai_tokens": 10000,
    },
    "enterprise": {
        "section_range": [13, 20],
        "component_range": [101, 300],
        "asset_count": [31, 100],
        "estimated_pages": 10,
        "estimated_ai_tokens": 25000,
    },
}

PERFORMANCE_SCORE_LABELS: Dict[int, str] = {
    95: "excellent",
    90: "great",
    85: "good",
    80: "fair",
    75: "needs-improvement",
    0: "poor",
}

SEO_LEVEL_MAP: Dict[str, str] = {
    "standard": "Basic meta tags and sitemap",
    "enhanced": "Open Graph, Twitter Cards, structured data",
    "comprehensive": "Full schema markup, hreflang, advanced robots",
}

VALID_HEX_COLOR_RE: str = r"^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$"

REQUIRED_SECTIONS: List[str] = ["navigation", "hero", "footer"]

ASSET_TYPE_MAP: Dict[str, List[str]] = {
    "Navbar": ["logo"],
    "Logo": ["logo", "brand-assets"],
    "HeroSection": ["hero-image", "background-image"],
    "HeroImage": ["hero-image", "illustration", "mockup"],
    "HeroVideo": ["video", "background-video"],
    "ServiceCard": ["icon", "service-image", "illustration"],
    "FeatureCard": ["icon", "illustration"],
    "ProductCard": ["product-image", "icon"],
    "PricingCard": ["icon", "illustration"],
    "PortfolioCard": ["project-image", "screenshot"],
    "CaseStudyCard": ["project-image", "logo"],
    "GalleryGrid": ["gallery-image", "photo"],
    "TeamCard": ["team-photo", "avatar", "headshot"],
    "TestimonialCard": ["avatar", "client-photo", "logo"],
    "BlogCard": ["blog-image", "thumbnail"],
    "ContactForm": ["background-image"],
    "TrustBadge": ["badge-logo", "certification-image"],
    "ImageWithText": ["content-image", "illustration"],
    "Avatar": ["avatar", "profile-photo"],
    "IconBox": ["icon"],
    "StatisticCard": ["icon"],
    "SocialIcons": ["social-icon"],
}


